<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Inicio',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-home',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2021-06-02 13:55:32',
                'updated_at' => '2022-07-07 09:32:02',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2021-06-02 13:55:32',
                'updated_at' => '2022-09-15 18:52:21',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => 11,
                'order' => 1,
                'created_at' => '2021-06-02 13:55:32',
                'updated_at' => '2021-06-02 10:08:02',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 11,
                'order' => 2,
                'created_at' => '2021-06-02 13:55:32',
                'updated_at' => '2021-06-02 10:08:05',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Herramientas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2021-06-02 13:55:32',
                'updated_at' => '2022-05-23 07:35:10',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2021-06-02 13:55:33',
                'updated_at' => '2021-06-02 10:07:22',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2021-06-02 13:55:33',
                'updated_at' => '2022-09-15 18:52:21',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2021-06-02 13:55:33',
                'updated_at' => '2022-09-15 18:52:21',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2021-06-02 13:55:33',
                'updated_at' => '2022-09-15 18:52:21',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 6,
                'created_at' => '2021-06-02 13:55:33',
                'updated_at' => '2022-09-15 18:52:21',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Seguridad',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2021-06-02 10:07:53',
                'updated_at' => '2022-05-23 07:35:10',
                'route' => NULL,
                'parameters' => '',
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Limpiar cache',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-refresh',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 7,
                'created_at' => '2021-06-25 14:03:59',
                'updated_at' => '2022-09-15 18:52:21',
                'route' => 'clear.cache',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Rubro Empresas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-group',
                'color' => NULL,
                'parent_id' => 15,
                'order' => 5,
                'created_at' => '2022-05-04 05:54:24',
                'updated_at' => '2022-08-07 10:16:17',
                'route' => 'voyager.rubro-busines.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Rubro Personas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => NULL,
                'parent_id' => 15,
                'order' => 4,
                'created_at' => '2022-05-04 05:57:07',
                'updated_at' => '2022-08-07 10:16:17',
                'route' => 'voyager.rubro-people.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Parametros',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-params',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2022-05-04 05:57:46',
                'updated_at' => '2022-05-23 07:35:10',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Trabajadores',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-person-digging',
                'color' => '#000000',
                'parent_id' => 15,
                'order' => 7,
                'created_at' => '2022-05-04 07:30:41',
                'updated_at' => '2022-08-07 10:16:17',
                'route' => 'people.index',
                'parameters' => 'null',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Empresas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-building',
                'color' => '#000000',
                'parent_id' => 15,
                'order' => 6,
                'created_at' => '2022-05-04 17:05:07',
                'updated_at' => '2022-08-07 10:16:17',
                'route' => 'busines.index',
                'parameters' => 'null',
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Perfil & Exp. Laboral',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-user-gear',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-05-09 07:47:52',
                'updated_at' => '2022-12-04 02:56:37',
                'route' => 'people-perfil-experience.index',
                'parameters' => 'null',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Perfil',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-building',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2022-05-10 01:36:03',
                'updated_at' => '2022-06-01 12:14:38',
                'route' => 'busines.perfil-view',
                'parameters' => 'null',
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Buscar Trabajadores',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-magnifying-glass',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2022-05-12 06:14:27',
                'updated_at' => '2022-06-02 05:27:23',
                'route' => 'search-work.index',
                'parameters' => 'null',
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Bandeja',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-mail',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-05-15 13:57:11',
                'updated_at' => '2022-05-31 18:36:50',
                'route' => 'message-busine.bandeja',
                'parameters' => 'null',
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Bandeja',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-mail',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2022-05-15 13:57:45',
                'updated_at' => '2022-05-31 18:36:01',
                'route' => 'message-people.bandeja',
                'parameters' => 'null',
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Perfil',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-user-gear',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2022-05-16 07:52:49',
                'updated_at' => '2022-06-02 05:40:34',
                'route' => 'beneficiary.perfil-view',
                'parameters' => 'null',
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Buscar Empresa',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-magnifying-glass',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2022-05-16 08:45:21',
                'updated_at' => '2022-06-02 05:26:37',
                'route' => 'search-busine.index',
                'parameters' => 'null',
            ),
            24 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Bandeja',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-mail',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2022-05-23 07:34:58',
                'updated_at' => '2022-05-31 18:38:12',
                'route' => 'message-beneficiary.bandeja',
                'parameters' => 'null',
            ),
            25 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Departamentos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-building',
                'color' => NULL,
                'parent_id' => 15,
                'order' => 2,
                'created_at' => '2022-06-25 15:43:46',
                'updated_at' => '2022-08-07 10:16:17',
                'route' => 'voyager.departments.index',
                'parameters' => NULL,
            ),
            26 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Ciudades',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-city',
                'color' => NULL,
                'parent_id' => 15,
                'order' => 3,
                'created_at' => '2022-06-25 15:46:29',
                'updated_at' => '2022-08-07 10:16:17',
                'route' => 'voyager.cities.index',
                'parameters' => NULL,
            ),
            27 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Professions',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-user-doctor',
                'color' => '#000000',
                'parent_id' => 15,
                'order' => 1,
                'created_at' => '2022-08-07 10:12:25',
                'updated_at' => '2022-08-07 10:16:17',
                'route' => 'voyager.professions.index',
                'parameters' => 'null',
            ),
            28 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Porta Folio',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-photo-film',
                'color' => '#000000',
                'parent_id' => 15,
                'order' => 8,
                'created_at' => '2022-09-09 08:24:02',
                'updated_at' => '2022-09-09 08:24:14',
                'route' => 'modelfolio.index',
                'parameters' => NULL,
            ),
            29 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'Registrar Modelos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-people-pulling',
                'color' => '#000000',
                'parent_id' => 15,
                'order' => 9,
                'created_at' => '2022-09-15 18:51:58',
                'updated_at' => '2022-09-18 08:43:20',
                'route' => 'registerModel.index',
                'parameters' => 'null',
            ),
        ));
        
        
    }
}